// <auto-generated />
namespace ToDoList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class v101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v101));
        
        string IMigrationMetadata.Id
        {
            get { return "202005021043306_v1.01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
